# Generated by Django 4.0.3 on 2022-03-09 12:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer', '0017_alter_customer_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='slug',
            field=models.SlugField(default='5ba34ebd-9', max_length=100),
        ),
    ]
