# Generated by Django 4.0.3 on 2022-03-09 09:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0002_alter_product_slug'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='stock',
            new_name='quantity_available',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='52e3b060-0', max_length=200),
        ),
    ]
