# Generated by Django 4.0.3 on 2022-03-09 09:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_rename_stock_product_quantity_available_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='brand',
        ),
        migrations.AlterField(
            model_name='product',
            name='slug',
            field=models.SlugField(default='405623d4-8', max_length=200),
        ),
        migrations.DeleteModel(
            name='Brand',
        ),
    ]
